env_id: "ALE/MsPacman-v5"
seed: 42
device: "mps"
full_action_space: false
frameskip: 4
repeat_action_probability: 0.25
frame_stack: 4
resize: [84, 84]
gray_scale: true
clip_rewards: true
gamma: 0.99
learning_rate: 0.0005       
batch_size: 32
buffer_size: 100000
start_learning_after: 5000
train_freq: 4
target_update_freq: 10000
exploration: "epsilon_greedy"
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay_frames: 1000000
total_frames: 300000
eval_episodes: 10
save_best: true
run_name: "lr0005-300k"